// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltodrbyibffuypqommpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0b2RyYnlpYmZmdXlwcW9tbXB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0NTQyMjksImV4cCI6MjA2MTAzMDIyOX0.VMZGvq5Q1hkIsAb0FCvUbPin_EPVyYFdp7Nox1PcHpc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);